databases:
  - name: crazy4cats
    databaseName: crazy4
    user: mysite

services:
  - type: web
    name: crazy4cats
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false